const products = [

  {
    id: 1,
    name:'18x7-8 Solideal Havalı',
    key:"18x7-8",
    type:"Havalı",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/lastik2.jpg', // Ürün resmi
  },
  {
    id: 2,
    name: '21x8-9 Solideal Dolgu',
    key:"21x8-9",
    type:"Dolgulu",
    description: 'Solideal havalı lastikler, dayanıklılığı ve konforu bir arada sunan, özellikle iş makineleri ve ağır hizmet araçları için tasarlanmış lastiklerdir.',
    image: '/images/siyah dolgu logolu.png',
  },
  {
    id: 3,
    name: '23x9-10 Solideal Dolgu',
    key:"23x9-10",
    type:"Dolgulu",
    description: 'Solideal havalı lastikler, ağır hizmet araçları ve iş makineleri için geliştirilmiş, dayanıklı ve konforlu lastiklerdir. Zorlu arazilerde üstün performans sunar.',
    image: '/images/siyah dolgu logolu.png',
  },
  {
    id: 4,
    name: '23x10-12 Solideal Havalı',
    key:"23x10-12",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 5,
    name: '28x9-15 Solideal İz Bırakmayan Dolgu',
    key:"28x9-15",
    type:"İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/iz bırakmayan dolgu logolu.png',
  },
  {
    id: 6,
    name: '18x7-8 Solideal Dolgu',
    key:"18x7-8",
    type:"Dolgulu",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/siyah dolgu logolu.png',
  },
  {
    id: 7,
    name:'18x7-8 Solideal İz Bırakmayan Havalı',
    key:"18x7-8",
    type:"Havalı,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 8,
    name:'18x7-8 Solideal İz Bırakmayan Dolgu',
    key:"18x7-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 9,
    name:'18x7-8 Rodaco İz Bırakmayan Dolgu',
    key:"18x7-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 10,
    name:'18x7-8 Rodaco Dolgu',
    key:"18x7-8",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  {
    id: 11,
    name:'21x8-9 Solideal İz Bırakmayan Dolgu',
    key:"21x8-9",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 12,
    name:'21x8-9 Solideal Havalı',
    key:"21x8-9",
    type:"Havalı",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/lastik2.jpg', // Ürün resmi
  },
  {
    id: 13,
    name:'21x8-9 Rodaco Dolgu',
    key:"21x8-9",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  {
    id: 14,
    name:'21x8-9 Rodaco İz Bırakmayan Dolgu',
    key:"21x8-9",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 15,
    name:'23x9-10 Solideal İz Bırakmayan Dolgu',
    key:"23x9-10",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 16,
    name:'23x9-10 Rodaco Dolgu',
    key:"23x9-10",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  {
    id: 17,
    name:'23x9-10 Rodaco İz Bırakmayan Dolgu',
    key:"23x9-10",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 18,
    name: '23x10-12 Solideal Dolgu',
    key:"23x10-12",
    type:"Dolgulu",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/siyah dolgu logolu.png',
  },
  {
    id: 19,
    name:'23x10-12 Solideal İz Bırakmayan Havalı',
    key:"23x10-12",
    type:"Havalı,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 20,
    name:'23x10-12 Solideal İz Bırakmayan Dolgu',
    key:"23x10-12",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 21,
    name:'23x10-12 Rodaco İz Bırakmayan Dolgu',
    key:"23x10-12",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 22,
    name:'23x10-12 Rodaco Dolgu',
    key:"23x10-12",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  {
    id: 23,
    name: '27x10-12 Solideal Dolgu',
    key:"27x10-12",
    type:"Dolgulu",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/siyah dolgu logolu.png',
  },
  {
    id: 24,
    name:'27x10-12 Solideal İz Bırakmayan Havalı',
    key:"27x10-12",
    type:"Havalı,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 25,
    name:'27x10-12 Solideal İz Bırakmayan Dolgu',
    key:"27x10-12",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 26,
    name:'27x10-12 Rodaco İz Bırakmayan Dolgu',
    key:"27x10-12",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 27,
    name:'27x10-12 Rodaco Dolgu',
    key:"27x10-12",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  {
    id: 28,
    name:'27x10-12 Solideal Havalı',
    key:"27x10-12",
    type:"Havalı",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/lastik2.jpg', // Ürün resmi
  },
  {
    id: 29,
    name: '28x9-15 Solideal Dolgu',
    key:"28x9-15",
    type:"Dolgulu",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/siyah dolgu logolu.png',
  },
  {
    id: 30,
    name:'28x9-15 Solideal İz Bırakmayan Havalı',
    key:"28x9-15",
    type:"Havalı,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 31,
    name:'28x9-15 Rodaco İz Bırakmayan Dolgu',
    key:"28x9-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 32,
    name:'28x9-15 Rodaco Dolgu',
    key:"28x9-15",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  {
    id: 33,
    name:'28x9-15 Solideal Havalı',
    key:"28x9-15",
    type:"Havalı",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/lastik2.jpg', // Ürün resmi
  },
  {
    id: 34,
    name: '250-15 Solideal Dolgu',
    key:"250-15",
    type:"Dolgulu",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/siyah dolgu logolu.png',
  },
  {
    id: 35,
    name:'250-15 Solideal İz Bırakmayan Havalı',
    key:"250-15",
    type:"Havalı,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 36,
    name:'250-15 Solideal İz Bırakmayan Dolgu',
    key:"250-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 37,
    name:'250-15 Rodaco Dolgu',
    key:"250-15",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  {
    id: 38,
    name:'250-15 Solideal Havalı',
    key:"250-15",
    type:"Havalı",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/lastik2.jpg', // Ürün resmi
  },
  {
    id: 39,
    name:'250-15 Rodeco İz Bırakmayan Dolgu',
    key:"250-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', // Ürün resmi
  },
  {
    id: 40,
    name: '300-15 Solideal Havalı',
    key:"300-15",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 41,
    name:'300-15 Solideal Dolgu',
    key:"300-15",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 42,
    name:'300-15 Solideal İz Bırakmayan Havalı',
    key:"300-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 43,
    name:'300-15 Solideal İz Bırakmayan Dolgu',
    key:"300-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 44,
    name:'300-15 Rodaco Dolgu',
    key:"300-15",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 45,
    name:'300-15 Rodaco İz Bırakmayan Dolgu',
    key:"300-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 46,
    name: '400-8 Solideal Havalı',
    key:"400-8",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 47,
    name: '500-8 Solideal Havalı',
    key:"500-8",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 48,
    name:'500-8 Solideal Dolgu',
    key:"500-8",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 49,
    name:'500-8 Solideal İz Bırakmayan Havalı',
    key:"500-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 50,
    name:'500-8 Solideal İz Bırakmayan Dolgu',
    key:"500-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 51,
    name:'500-8 Rodaco Dolgu',
    key:"500-8",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 52,
    name:'500-8 Rodaco İz Bırakmayan Dolgu',
    key:"500-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 53,
    name: '600-9 Solideal Havalı',
    key:"600-9",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 54,
    name:'600-9 Solideal Dolgu',
    key:"600-9",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 55,
    name:'600-9 Solideal İz Bırakmayan Havalı',
    key:"600-9",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 56,
    name:'600-9 Solideal İz Bırakmayan Dolgu',
    key:"600-9",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 57,
    name:'600-9 Rodaco Dolgu',
    key:"600-9",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 58,
    name:'600-9 Rodaco İz Bırakmayan Dolgu',
    key:"600-9",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 59,
    name: '650-10 Solideal Havalı',
    key:"650-10",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 60,
    name:'650-10 Solideal Dolgu',
    key:"650-10",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 61,
    name:'650-10 Solideal İz Bırakmayan Havalı',
    key:"650-10",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 62,
    name:'650-10 Solideal İz Bırakmayan Dolgu',
    key:"650-10",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 63,
    name:'650-10 Rodaco Dolgu',
    key:"650-10",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 64,
    name:'650-10 Rodaco İz Bırakmayan Dolgu',
    key:"650-10",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 65,
    name: '700-12 Solideal Havalı',
    key:"700-12",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 66,
    name:'700-12 Solideal Dolgu',
    key:"700-12",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 67,
    name:'700-12 Solideal İz Bırakmayan Havalı',
    key:"700-12",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 68,
    name:'700-12 Solideal İz Bırakmayan Dolgu',
    key:"700-12",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 69,
    name:'700-12 Rodaco Dolgu',
    key:"700-12",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 70,
    name:'700-12 Rodaco İz Bırakmayan Dolgu',
    key:"700-12",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 71,
    name: '700-15 Solideal Havalı',
    key:"700-15",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 72,
    name:'700-15 Solideal Dolgu',
    key:"700-15",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 73,
    name:'700-15 Solideal İz Bırakmayan Havalı',
    key:"700-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 74,
    name:'700-15 Solideal İz Bırakmayan Dolgu',
    key:"700-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 75,
    name:'700-15 Rodaco Dolgu',
    key:"700-15",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 76,
    name:'700-15 Rodaco İz Bırakmayan Dolgu',
    key:"700-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 77,
    name: '750-10 Solideal Havalı',
    key:"750-10",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
 { id: 78,
    name: '750-15 Solideal Havalı',
    key:"750-15",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 79,
    name:'750-15 Solideal Dolgu',
    key:"750-15",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 80,
    name:'750-15 Solideal İz Bırakmayan Dolgu',
    key:"750-15",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 81,
    name: '750-16 Solideal Havalı',
    key:"750-16",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 82,
    name: '825-25 Solideal Havalı',
    key:"825-25",
    type:"Havalı",
    description: 'Solideal havalı lastikler, zorlu koşullara dayanıklı, iş makineleri ve ağır hizmet araçları için üretilmiş, güvenilir ve konforlu lastiklerdir.',
    image: '/images/lastik2.jpg',
  },
  {
    id: 83,
    name:'825-25 Solideal Dolgu',
    key:"825-25",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 84,
    name:'825-25 Solideal İz Bırakmayan Havalı',
    key:"825-25",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/uriotomotivlastik3.png', 
  },
  {
    id: 85,
    name:'825-25 Solideal İz Bırakmayan Dolgu',
    key:"825-25",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 86,
    name:'825-25 Rodaco Dolgu',
    key:"825-25",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 87,
    name:'825-25 Rodaco İz Bırakmayan Dolgu',
    key:"825-25",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 88,
    name:'140/55-9 Solideal Dolgu',
    key:"140/55-9",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 89,
    name:'140/55-9 Solideal İz Bırakmayan Dolgu',
    key:"140/55-9",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 90,
    name:'140/55-9 Rodaco Dolgu',
    key:"140/55-9",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 91,
    name:'140/55-9 Rodaco İz Bırakmayan Dolgu',
    key:"140/55-9",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 92,
    name:'15x4 1/2-8 Solideal Dolgu',
    key:"15x4 1/2-8",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 93,
    name:'15x4 1/2-8 Solideal İz Bırakmayan Dolgu',
    key:"15x4 1/2-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 94,
    name:'15x4 1/2-8 Rodaco Dolgu',
    key:"15x4 1/2-8",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 95,
    name:'15x4 1/2-8 Rodaco İz Bırakmayan Dolgu',
    key:"15x4 1/2-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 96,
    name:'16x6-8 Solideal Dolgu',
    key:"16x6-8",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 97,
    name:'16x6-8 Solideal İz Bırakmayan Dolgu',
    key:"16x6-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 98,
    name:'16x6-8 Rodaco Dolgu',
    key:"16x6-8",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 99,
    name:'16x6-8 Rodaco İz Bırakmayan Dolgu',
    key:"16x6-8",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  {
    id: 100,
    name:'200/50-10 Solideal Dolgu',
    key:"200/50-10",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah dolgu logolu.png', 
  },
  {
    id: 101,
    name:'200/50-10  Solideal İz Bırakmayan Dolgu',
    key:"200/50-10",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/iz bırakmayan dolgu logolu.png', 
  },
  {
    id: 102,
    name:'200/50-10  Rodaco Dolgu',
    key:"200/50-10",
    type:"Dolgu",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah rodaco dolgu logolu.png', 
  },
  { id: 103,
    name:'200/50-10  Rodaco İz Bırakmayan Dolgu',
    key:"200/50-10",
    type:"Dolgu,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/rodaco dolgu iz bırakmayan siyah logolu.png', 
  },
  { id: 104,
    name:'10 1/2x5x6 1/2 Solideal İz Bırakmayan Çemberli',
    key:"10 1/2x5x6 1/2",
    type:"Çemberli,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/beyaz çemberli uri logolu.png', 
  },
  { id: 105,
    name:'10 1/2x5x6 1/2 Solideal Çemberli',
    key:"10 1/2x5x6 1/2",
    type:"Çemberli,",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah çemberli logolu.png', 
  },
  { id: 106,
    name:'16x6x10 1/2 Solideal İz Bırakmayan Çemberli',
    key:"16x6x10 1/2",
    type:"Çemberli,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/beyaz çemberli uri logolu.png', 
  },
  { id: 107,
    name:'16x6x10 1/2 Solideal Çemberli',
    key:"16x6x10 1/2",
    type:"Çemberli,",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah çemberli logolu.png', 
  },
  { id: 108,
    name:'16 1/4x7x11 1/4 Solideal İz Bırakmayan Çemberli',
    key:"16 1/4x7x11 1/4",
    type:"Çemberli,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/beyaz çemberli uri logolu.png', 
  },
  { id: 109,
    name:'16 1/4x7x11 1/4 Solideal Çemberli',
    key:"16 1/4x7x11 1/4",
    type:"Çemberli,",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah çemberli logolu.png', 
  },
  { id: 110,
    name:'18x8x12 1/8 Solideal İz Bırakmayan Çemberli',
    key:"18x8x12 1/8",
    type:"Çemberli,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/beyaz çemberli uri logolu.png', 
  },
  { id: 111,
    name:'18x8x12 1/8 Solideal Çemberli',
    key:"18x8x12 1/8",
    type:"Çemberli,",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah çemberli logolu.png', 
  },
  { id: 112,
    name:'21x7x15 Solideal İz Bırakmayan Çemberli',
    key:"21x7x15",
    type:"Çemberli,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/beyaz çemberli uri logolu.png', 
  },
  { id: 113,
    name:'21x7x15 Solideal Çemberli',
    key:"21x7x15",
    type:"Çemberli,",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah çemberli logolu.png', 
  },
  { id: 114,
    name:'21x8x15 Solideal İz Bırakmayan Çemberli',
    key:"21x8x15",
    type:"Çemberli,İz Bırakmayan Lastik",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/beyaz çemberli uri logolu.png', 
  },
  { id: 115,
    name:'21x8x15 Solideal Çemberli',
    key:"21x8x15",
    type:"Çemberli,",
    description: 'Solideal havalı lastikler, sağlam yapısı ve yüksek konforuyla iş makineleri ve ağır araçlar için ideal olup, uzun ömürlü kullanım sunar.',
    image: '/images/siyah çemberli logolu.png', 
  },

  
  
  
  
  
  
];

export { products };